/**
 * Checked-in corpus of TeX strings REAL models actually emitted (harvested via
 * `npx tsx --env-file=.env scripts/harvest.mjs` against Groq/OpenRouter, plus
 * strings observed in earlier live runs -- see the harvest handoff note at
 * `docs/superpowers/notes/2026-07-31-handoff.md`). `harvest.json` at the repo
 * root is generated, gitignored output; this file is the durable extract of
 * it, hand-picked and tagged with what SHOULD happen when the string is run
 * through `checkStepRenderable`.
 *
 * This exists because every one of the bugs this fixture guards against
 * passed a fully green unit suite written against a fake client and
 * hand-written happy-path fixtures -- see docs/superpowers/notes/2026-07-31-handoff.md
 * section 4. A corpus of strings a model actually said is the only test data
 * that can catch this class of bug.
 */

export interface CorpusEntry {
  /** The raw TeX a model emitted (or a hand-written adversarial variant of one). */
  tex: string;
  /** Whether this string is expected to survive the real render path. */
  expectRenderable: boolean;
  /** Where this string came from, for anyone auditing the corpus later. */
  source: string;
}

export const MODEL_OUTPUT_CORPUS: CorpusEntry[] = [
  // --- Not renderable: unsupported TeX outside the stroke engine's subset ---
  {
    tex: "20.4 \\, \\text{m}",
    expectRenderable: false,
    source: "harvest.mjs live run, openrouter, 'ball thrown up' question -- \\, and \\text{} unsupported",
  },
  {
    tex: "x = \\frac{2}{4} \\/\\boxed{\\frac{1}{2}}, \\quad",
    expectRenderable: false,
    source: "2026-07-18 live run, openrouter -- \\boxed, \\quad, and \\/ all unsupported (handoff Bug 4)",
  },
  {
    tex: "\\quad",
    expectRenderable: false,
    source: "2026-07-18 live run -- bare \\quad, unsupported spacing command",
  },
  {
    tex: "\\left( x \\right)",
    expectRenderable: false,
    source: "common model habit -- \\left/\\right sizing commands, explicitly unsupported per tools.ts",
  },
  {
    tex: "2 \\cdot 3",
    expectRenderable: false,
    source: "common model habit -- \\cdot, explicitly unsupported per tools.ts (use \\times)",
  },
  {
    tex: "\\text{cm}",
    expectRenderable: false,
    source: "common model habit -- \\text{}, explicitly unsupported per tools.ts",
  },
  {
    tex: "(x^2 - 9)/(x - 3) = (x + 3)(x - 3)/(x - 3) = x + 3",
    expectRenderable: false,
    source:
      "harvest.mjs live run, openrouter, 'simplify' question -- valid TeX but 959px wide on a 900px board (LayoutOverflowError)",
  },

  // --- Renderable: within the stroke engine's TeX subset ---
  { tex: "2x^2 + 5x - 3 = 0", expectRenderable: true, source: "harvest.mjs question prompt, always renderable" },
  {
    tex: "x = \\frac{-5 \\pm \\sqrt{49}}{4}",
    expectRenderable: true,
    source: "quadratic formula step -- \\frac, \\pm, \\sqrt all supported",
  },
  { tex: "x = \\frac{1}{2}", expectRenderable: true, source: "solved-form step -- \\frac supported" },
  { tex: "v_0", expectRenderable: true, source: "subscript -- supported" },
  { tex: "\\Delta = 25", expectRenderable: true, source: "discriminant step -- \\Delta supported" },
  { tex: "x^2", expectRenderable: true, source: "superscript -- supported" },

  // Additional real strings from harvest.json (repo-root, gitignored, generated by
  // scripts/harvest.mjs) -- the full derivation for the "ball thrown up" question, all of
  // which DID render, surrounding the one step that didn't.
  { tex: "v^2 = u^2 + 2as", expectRenderable: true, source: "harvest.json, openrouter, kinematics anchor step" },
  {
    tex: "0 = 20^2 - 2 \\times 9.8 \\times s",
    expectRenderable: true,
    source: "harvest.json, openrouter -- \\times supported",
  },
  { tex: "0 = 400 - 19.6s", expectRenderable: true, source: "harvest.json, openrouter" },
  { tex: "19.6s = 400", expectRenderable: true, source: "harvest.json, openrouter" },
  { tex: "s = 400 / 19.6", expectRenderable: true, source: "harvest.json, openrouter" },
  { tex: "s = 20.4", expectRenderable: true, source: "harvest.json, openrouter -- the step right before the bad one" },
];
